[2025-04-29T06:08:05.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T06:08:05.104+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T05:59:51.670410+00:00 [queued]>
[2025-04-29T06:08:05.158+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T05:59:51.670410+00:00 [queued]>
[2025-04-29T06:08:05.161+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-29T06:08:05.285+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): prepare_data> on 2025-04-29 05:59:51.670410+00:00
[2025-04-29T06:08:05.331+0000] {standard_task_runner.py:72} INFO - Started process 667 to run task
[2025-04-29T06:08:05.363+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'all_classification_pipeline', 'prepare_data', 'manual__2025-04-29T05:59:51.670410+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/classification_pipeline.py', '--cfg-path', '/tmp/tmpoc6237b8']
[2025-04-29T06:08:05.395+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask prepare_data
[2025-04-29T06:08:05.801+0000] {task_command.py:467} INFO - Running <TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T05:59:51.670410+00:00 [running]> on host 6654e0e8303a
[2025-04-29T06:08:06.232+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='all_classification_pipeline' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T05:59:51.670410+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T05:59:51.670410+00:00'
[2025-04-29T06:08:06.240+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T06:08:06.388+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/scripts/prepare_data.py", line 14, in make_manifest
    train, rest = train_test_split(items, test_size=val_size+test_size, random_state=seed, stratify=[l for _,l in items])
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2851, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2481, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2025-04-29T06:08:06.460+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=all_classification_pipeline, task_id=prepare_data, run_id=manual__2025-04-29T05:59:51.670410+00:00, execution_date=20250429T055951, start_date=20250429T060805, end_date=20250429T060806
[2025-04-29T06:08:06.674+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T06:08:06.678+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task prepare_data (With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.; 667)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/scripts/prepare_data.py", line 14, in make_manifest
    train, rest = train_test_split(items, test_size=val_size+test_size, random_state=seed, stratify=[l for _,l in items])
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2851, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/home/airflow/.local/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2481, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2025-04-29T06:08:06.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-29T06:08:06.898+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T06:08:06.984+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
